### ISSUE TITLE
Addiing an ontology to the config causes the system to fail

### ISSUE THREAD

**Issue by javadch** [TIBHannover/vocol#4]
When the system is up and running using the Dockerfile, by adding the information of the first ontology (e.g., SNO) on its GitHub repo, the system fails to load the ontology and crashes so that the container should be killed and removed. Here is the error message:

`Error: Could not find the include file "dataProtectionScript"
    at getIncludePath (/home/tib/vocol/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/home/tib/vocol/node_modules/ejs/lib/ejs.js:309:17)
    at /home/tib/vocol/node_modules/ejs/lib/ejs.js:719:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/tib/vocol/node_modules/ejs/lib/ejs.js:695:15)
    at includeSource (/home/tib/vocol/node_modules/ejs/lib/ejs.js:313:9)
    at /home/tib/vocol/node_modules/ejs/lib/ejs.js:719:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/home/tib/vocol/node_modules/ejs/lib/ejs.js:695:15)
    at Template.compile (/home/tib/vocol/node_modules/ejs/lib/ejs.js:572:12)`

**Comment by vitalis-wiens** [comment]
fixed by adding manually the dataProtectionScript to github repo
